#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🚀 Codex CLI + Nebius Token Factory Setup${NC}\n"

# Step 1: Check Codex CLI installation
echo -e "${BLUE}Step 1: Checking Codex CLI installation...${NC}"
if ! command -v codex &> /dev/null; then
    echo -e "${YELLOW}⚠️  Codex CLI not found. Install it with:${NC}"
    echo "  npm install -g @openai/codex"
    exit 1
fi
echo -e "${GREEN}✓ Codex CLI found: $(codex --version)${NC}\n"

# Step 2: Create config directory
echo -e "${BLUE}Step 2: Setting up Codex configuration directory...${NC}"
CODEX_DIR="$HOME/.codex"
if [ ! -d "$CODEX_DIR" ]; then
    mkdir -p "$CODEX_DIR"
    echo -e "${GREEN}✓ Created $CODEX_DIR${NC}"
else
    echo -e "${GREEN}✓ $CODEX_DIR already exists${NC}"
fi
echo

# Step 3: Get API key
echo -e "${BLUE}Step 3: Nebius Token Factory Authentication${NC}"
echo "Your API key will be stored in ~/.bashrc or ~/.zshrc"
echo "You can also set it manually: export NEBIUS_API_KEY=your-key"
echo
read -sp "Enter your Nebius Token Factory API key: " NEBIUS_API_KEY
echo
if [ -z "$NEBIUS_API_KEY" ]; then
    echo -e "${YELLOW}⚠️  No API key provided. Skipping credential setup.${NC}"
    echo "You can set it later with: export NEBIUS_API_KEY=your-key"
else
    # Detect shell and add to appropriate profile
    if [ -n "$ZSH_VERSION" ]; then
        PROFILE_FILE="$HOME/.zshrc"
    elif [ -n "$BASH_VERSION" ]; then
        PROFILE_FILE="$HOME/.bashrc"
    else
        PROFILE_FILE="$HOME/.bashrc"  # Default to bashrc
    fi

    # Add to shell profile if not already there
    if ! grep -q "NEBIUS_API_KEY" "$PROFILE_FILE"; then
        echo "export NEBIUS_API_KEY='$NEBIUS_API_KEY'" >> "$PROFILE_FILE"
        echo -e "${GREEN}✓ Added NEBIUS_API_KEY to $PROFILE_FILE${NC}"
    else
        echo -e "${GREEN}✓ NEBIUS_API_KEY already in $PROFILE_FILE${NC}"
    fi

    # Also export for current session
    export NEBIUS_API_KEY
fi
echo

# Step 4: Generate config.toml
echo -e "${BLUE}Step 4: Generating Codex configuration...${NC}"
CONFIG_FILE="$CODEX_DIR/config.toml"

cat > "$CONFIG_FILE" << 'EOF'
# Codex CLI + Nebius Token Factory Configuration
# Generated by setup-codex-nebius.sh

# Set default provider and profile
default_provider = "nebius_token_factory"
default_profile = "nebius-token-factory"

# ============================================
# PROVIDER DEFINITIONS
# ============================================

[model_providers.nebius_token_factory]
name = "Nebius Token Factory"
base_url = "https://api.tokenfactory.nebius.com/v1/chat/completions"
env_key = "NEBIUS_API_KEY"

[model_providers.nebius_fast]
name = "Nebius Fast (Mistral)"
base_url = "https://api.tokenfactory.nebius.com/v1/chat/completions"
env_key = "NEBIUS_API_KEY"

# ============================================
# PROFILE DEFINITIONS
# ============================================

# Balanced - good for most tasks
[profiles.nebius-token-factory]
model_provider = "nebius_token_factory"
model_name = "nebius/NousResearch/Hermes-4-405B"
max_tokens = 4096
temperature = 0.7

# Fast - quick suggestions and completions
[profiles.nebius-fast]
model_provider = "nebius_fast"
model_name = "nebius/google/Gemma-3-27b-it"
max_tokens = 2048
temperature = 0.5

# Precise - detailed analysis and explanations
[profiles.nebius-precise]
model_provider = "nebius_token_factory"
model_name = "nebius/Qwen/Qwen3-Coder-480B-A35B-Instruct"
max_tokens = 8192
temperature = 0.3

# ============================================
# USAGE
# ============================================
#
# Default (balanced):
#   codex "Write a Python function"
#
# Fast profile:
#   codex --profile nebius-fast "Quick function"
#
# Precise profile:
#   codex --profile nebius-precise "Detailed explanation"
#
# Override at runtime:
#   codex -c temperature=0.3 "Be precise"
#   codex -c max_tokens=1024 "Shorter response"
#
EOF

echo -e "${GREEN}✓ Generated $CONFIG_FILE${NC}"
echo

# Step 5: Verify configuration
echo -e "${BLUE}Step 5: Verifying setup...${NC}"
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${GREEN}✓ Configuration file exists${NC}"

    # Check if TOML is valid by trying to read it
    if grep -q "model_providers" "$CONFIG_FILE"; then
        echo -e "${GREEN}✓ Configuration looks valid${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  Configuration file not found${NC}"
    exit 1
fi
echo

# Step 6: Test connection (optional)
echo -e "${BLUE}Step 6: Test connection (optional)${NC}"
read -p "Test connection to Nebius Token Factory? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ -z "$NEBIUS_API_KEY" ]; then
        echo -e "${YELLOW}⚠️  API key not set. Load it first:${NC}"
        echo "  source $PROFILE_FILE"
        echo "  $0"
    else
        echo "Testing connection to Nebius Token Factory API..."
        if curl -s -H "Authorization: Bearer $NEBIUS_API_KEY" \
            https://api.tokenfactory.nebius.com/v1/models > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Connection successful!${NC}"
        else
            echo -e "${YELLOW}⚠️  Connection test failed. Check your API key.${NC}"
        fi
    fi
fi
echo

# Summary
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo
echo "Configuration file: $CONFIG_FILE"
echo
echo "Next steps:"
echo "  1. Load your shell profile (if you added the API key):"
echo "     source $PROFILE_FILE"
echo
echo "  2. Try Codex with Token Factory:"
echo "     codex 'Write a Python function to validate email'"
echo
echo "  3. Use different profiles:"
echo "     codex --profile nebius-fast 'Quick code'"
echo "     codex --profile nebius-precise 'Detailed explanation'"
echo
echo "  4. Read the full guide:"
echo "     https://github.com/opencolin/nebius-skill/blob/main/CODEX_CLI_SETUP_GUIDE.md"
echo
echo -e "${BLUE}Happy coding!${NC}"
